language: python
cache: pip
dist: xenial
python:
   - "3.6"
   - "3.7"
   - "3.8"
env:
  matrix:
    - export PANDAS_VERSION=0.23.4     && export NUMPY_VERSION=1.17.2
    - export PANDAS_VERSION=0.24.1     && export NUMPY_VERSION=1.17.2
    - export PANDAS_VERSION=0.25.1     && export NUMPY_VERSION=1.17.2
    - export NUMPY_VERSION=1.16.4      && export PANDAS_VERSION=0.25.1
    - export NUMPY_VERSION=1.15.4      && export PANDAS_VERSION=0.25.1
before_install:
  - ls
  # - sudo apt-get update
install: "make"
script:
  # enforce formatting
  - make check_format
  # command to run tests
  - make test
after_success:
  - coveralls
# Don't want notifications
notifications:
  email: false
